/* Generated By:JavaCC: Do not edit this line. javinhaConstants.java */
package foo2;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface javinhaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int LTHEN = 9;
  /** RegularExpression Id. */
  int LENGHT = 10;
  /** RegularExpression Id. */
  int CLASS = 11;
  /** RegularExpression Id. */
  int PUBLIC = 12;
  /** RegularExpression Id. */
  int EXTENDS = 13;
  /** RegularExpression Id. */
  int THIS = 14;
  /** RegularExpression Id. */
  int NEW = 15;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 16;
  /** RegularExpression Id. */
  int DIGIT = 17;
  /** RegularExpression Id. */
  int BOOL = 18;
  /** RegularExpression Id. */
  int ID = 19;
  /** RegularExpression Id. */
  int LIT = 20;
  /** RegularExpression Id. */
  int INT = 21;
  /** RegularExpression Id. */
  int LPAREN = 22;
  /** RegularExpression Id. */
  int RPAREN = 23;
  /** RegularExpression Id. */
  int LBRACK = 24;
  /** RegularExpression Id. */
  int RBRACK = 25;
  /** RegularExpression Id. */
  int BOOLEAN = 26;
  /** RegularExpression Id. */
  int WHILE = 27;
  /** RegularExpression Id. */
  int IF = 28;
  /** RegularExpression Id. */
  int ELSE = 29;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"&&\"",
    "\"<\"",
    "\"lenght\"",
    "\"class\"",
    "\"public\"",
    "\"extends\"",
    "\"this\"",
    "\"new\"",
    "<INTEGER_LITERAL>",
    "<DIGIT>",
    "<BOOL>",
    "<ID>",
    "<LIT>",
    "\"int\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"boolean\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\";\"",
    "\"{ public static void main ( String []\"",
    "\"{\"",
    "\"}\"",
    "\"\"",
    "\"return\"",
    "\",\"",
    "\"System.out.println\"",
    "\"=\"",
    "\".\"",
    "\"!\"",
  };

}
