/* Generated By:JavaCC: Do not edit this line. javinhaConstants.java */
package foo2;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface javinhaConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int AND = 8;
  /** RegularExpression Id. */
  int LTHEN = 9;
  /** RegularExpression Id. */
  int EQUALS = 10;
  /** RegularExpression Id. */
  int BOOLEAN = 11;
  /** RegularExpression Id. */
  int STRING = 12;
  /** RegularExpression Id. */
  int WHILE = 13;
  /** RegularExpression Id. */
  int IF = 14;
  /** RegularExpression Id. */
  int ELSE = 15;
  /** RegularExpression Id. */
  int LENGHT = 16;
  /** RegularExpression Id. */
  int CLASS = 17;
  /** RegularExpression Id. */
  int RETURN = 18;
  /** RegularExpression Id. */
  int STATIC = 19;
  /** RegularExpression Id. */
  int VOID = 20;
  /** RegularExpression Id. */
  int MAIN = 21;
  /** RegularExpression Id. */
  int PUBLIC = 22;
  /** RegularExpression Id. */
  int EXTENDS = 23;
  /** RegularExpression Id. */
  int SYSTEM = 24;
  /** RegularExpression Id. */
  int OUT = 25;
  /** RegularExpression Id. */
  int PRINTLN = 26;
  /** RegularExpression Id. */
  int THIS = 27;
  /** RegularExpression Id. */
  int INT = 28;
  /** RegularExpression Id. */
  int NEW = 29;
  /** RegularExpression Id. */
  int INTEGER_LITERAL = 30;
  /** RegularExpression Id. */
  int DIGIT = 31;
  /** RegularExpression Id. */
  int BOOL = 32;
  /** RegularExpression Id. */
  int ID = 33;
  /** RegularExpression Id. */
  int LIT = 34;
  /** RegularExpression Id. */
  int SCOLON = 35;
  /** RegularExpression Id. */
  int COMMA = 36;
  /** RegularExpression Id. */
  int DOT = 37;
  /** RegularExpression Id. */
  int LPAREN = 38;
  /** RegularExpression Id. */
  int RPAREN = 39;
  /** RegularExpression Id. */
  int LBRACK = 40;
  /** RegularExpression Id. */
  int RBRACK = 41;
  /** RegularExpression Id. */
  int LCHAVE = 42;
  /** RegularExpression Id. */
  int RCHAVE = 43;
  /** RegularExpression Id. */
  int SINGLE_LINE_COMMENT = 47;
  /** RegularExpression Id. */
  int FORMAL_COMMENT = 48;
  /** RegularExpression Id. */
  int MULTI_LINE_COMMENT = 49;

  /** Lexical state. */
  int DEFAULT = 0;
  /** Lexical state. */
  int IN_SINGLE_LINE_COMMENT = 1;
  /** Lexical state. */
  int IN_FORMAL_COMMENT = 2;
  /** Lexical state. */
  int IN_MULTI_LINE_COMMENT = 3;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"&&\"",
    "\"<\"",
    "\"=\"",
    "\"boolean\"",
    "\"String\"",
    "\"while\"",
    "\"if\"",
    "\"else\"",
    "\"lenght\"",
    "\"class\"",
    "\"return\"",
    "\"static\"",
    "\"void\"",
    "\"main\"",
    "\"public\"",
    "\"extends\"",
    "\"System\"",
    "\"out\"",
    "\"println\"",
    "\"this\"",
    "\"int\"",
    "\"new\"",
    "<INTEGER_LITERAL>",
    "<DIGIT>",
    "<BOOL>",
    "<ID>",
    "<LIT>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"[\"",
    "\"]\"",
    "\"{\"",
    "\"}\"",
    "\"//\"",
    "<token of kind 45>",
    "\"/*\"",
    "<SINGLE_LINE_COMMENT>",
    "\"*/\"",
    "\"*/\"",
    "<token of kind 50>",
    "\"!\"",
  };

}
